spring:
  application:
    name: fluxjwt

  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      database: AUTH_JWT
      username: root
      password: root!


  security:
    user:
      name: admin
      password: admin

server:
  port: 8081